version: '3.8'
services:
  movies:
    image: sravanthi777/paymovies:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3
  train:
    image: sravanthi777/paytrain:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3
  dth:
    image: sravanthi777/paydthh:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3
  recharge:
    image: sravanthi777/payrecharge:latest
    ports:
      - "84:80"
    deploy:
      replicas: 3
